package com.fimet.event;

public enum ParserEvent {
	PARSER_DELETED,
	PARSER_INSERTED,
	PARSER_UPDATED,
	PARSER_REMOVED,
	PARSER_LOADED,
	FIELDGROUP_DELETED,
	FIELDGROUP_INSERTED,
	FIELDGROUP_UPDATED,
	FIELDGROUP_REMOVED,
	FIELDGROUP_LOADED;
}
