package com.fimet.event;

public enum SimulatorEvent {
	SIMULATOR_MODEL_INSERTED,
	SIMULATOR_MODEL_UPDATED,
	SIMULATOR_MODEL_DELETED,
	SIMULATOR_INSERTED,
	SIMULATOR_UPDATED,
	SIMULATOR_DELETED,
	SIMULATOR_REMOVED,
	SIMULATOR_LOADED,
	SIMULATOR_CONNECTED,
	SIMULATOR_CONNECTING,
	SIMULATOR_DISCONNECTED,
	SIMULATOR_MANAGER_RELOADED;
}
