package com.fimet.event;

public enum NetEvent {
	SOCKET_INSERTED,
	SOCKET_UPDATED,
	SOCKET_DELETED,
	SOCKET_LOADED,
	SOCKET_REMOVED,
	SOCKET_CONNECTED,
	SOCKET_CONNECTING,
	SOCKET_DISCONNECTED,
	SOCKET_MANAGER_RELOADED;
}
