package com.fimet.event;

public enum EnviromentEvent {
	ENVIROMENT_INSERTED,
	ENVIROMENT_UPDATED,
	ENVIROMENT_DELETED,
	ENVIROMENT_CONNECTED,
	ENVIROMENT_CONNECTING,
	ENVIROMENT_DISCONNECTED,
	ENVIROMENT_MANAGER_RELOADED,
	FTP_INSERTED,
	FTP_UPDATED,
	FTP_DELETED,
	FTP_REMOVED,
	FTP_CONNECTED,
	FTP_CONNECTING,
	FTP_DISCONNECTED,
	FTP_MANAGER_RELOADED;
}
